### ISSUE TITLE
vite error

### ISSUE THREAD

**Issue by Giddyware** [Giddyware/openSeaClone#4]
![2023-04-28 01_05_02-Vite + React](https://user-images.githubusercontent.com/64388792/235015822-5145e597-d1b7-4908-87e8-4ea17abff491.png)

**Comment by princemuel** [comment]
This issue is due to your import in the Header component.

import IconName from "react-icons/bi"; // There is no default import

import { IconName } from "react-icons/bi"; // import like this instead
